/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author ASUS
 */

import com.toedter.calendar.JDateChooser;
import java.sql.*;
import databaseUtility.Connector;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class RegistrationView extends javax.swing.JFrame {

    /**
     * Creates new form NewRegisrasi
     */
    public RegistrationView() {
        initComponents();
        this.genderButtonGroup.add(radioButtonMale);
        this.genderButtonGroup.add(radioButtonFemale);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        genderButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelKeterangan = new javax.swing.JLabel();
        pANEL = new javax.swing.JPanel();
        NAMA_LENGKAP = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        newEmail = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        newpassword = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        TGLLAHIR = new javax.swing.JLabel();
        TGLLAHIR1 = new javax.swing.JLabel();
        buttonCreateAccount = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jDateDateBirth = new com.toedter.calendar.JDateChooser();
        NAMA_LENGKAP1 = new javax.swing.JLabel();
        radioButtonMale = new javax.swing.JRadioButton();
        radioButtonFemale = new javax.swing.JRadioButton();
        newpassword1 = new javax.swing.JLabel();
        jTextPhoneNumber = new javax.swing.JTextField();
        buttonBackToLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Registrasi");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/telyu.png"))); // NOI18N

        labelKeterangan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labelKeterangan.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelKeterangan))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelKeterangan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pANEL.setBackground(new java.awt.Color(153, 153, 153));
        pANEL.setForeground(new java.awt.Color(153, 153, 153));

        NAMA_LENGKAP.setBackground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        NAMA_LENGKAP.setForeground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP.setText("NAMA LENGKAP");

        jTextFieldName.setBackground(new java.awt.Color(204, 204, 204));

        newEmail.setBackground(new java.awt.Color(255, 255, 255));
        newEmail.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newEmail.setForeground(new java.awt.Color(255, 255, 255));
        newEmail.setText("E-MAIL");

        jTextFieldEmail.setBackground(new java.awt.Color(204, 204, 204));

        newpassword.setBackground(new java.awt.Color(255, 255, 255));
        newpassword.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newpassword.setForeground(new java.awt.Color(255, 255, 255));
        newpassword.setText("PASSWORD");

        jPasswordField.setBackground(new java.awt.Color(204, 204, 204));

        TGLLAHIR.setBackground(new java.awt.Color(255, 255, 255));
        TGLLAHIR.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        TGLLAHIR.setForeground(new java.awt.Color(255, 255, 255));
        TGLLAHIR.setText("TANGGAL LAHIR");

        TGLLAHIR1.setBackground(new java.awt.Color(255, 255, 255));
        TGLLAHIR1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        TGLLAHIR1.setForeground(new java.awt.Color(255, 255, 255));
        TGLLAHIR1.setText("ALAMAT");

        buttonCreateAccount.setBackground(new java.awt.Color(102, 102, 102));
        buttonCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreateAccount.setText("BUAT AKUN");

        jTextAreaAddress.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane2.setViewportView(jTextAreaAddress);

        jDateDateBirth.setBackground(new java.awt.Color(204, 204, 204));

        NAMA_LENGKAP1.setBackground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        NAMA_LENGKAP1.setForeground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP1.setText("JENIS KELAMIN");

        radioButtonMale.setBackground(new java.awt.Color(153, 153, 153));
        radioButtonMale.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonMale.setText("Laki-Laki");
        radioButtonMale.setToolTipText("");

        radioButtonFemale.setBackground(new java.awt.Color(153, 153, 153));
        radioButtonFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonFemale.setText("Perempuan");

        newpassword1.setBackground(new java.awt.Color(255, 255, 255));
        newpassword1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newpassword1.setForeground(new java.awt.Color(255, 255, 255));
        newpassword1.setText("NOMOR HP");

        jTextPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));

        buttonBackToLogin.setBackground(new java.awt.Color(102, 102, 102));
        buttonBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonBackToLogin.setText("KEMBALI");

        javax.swing.GroupLayout pANELLayout = new javax.swing.GroupLayout(pANEL);
        pANEL.setLayout(pANELLayout);
        pANELLayout.setHorizontalGroup(
            pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pANELLayout.createSequentialGroup()
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pANELLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NAMA_LENGKAP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newEmail)
                                .addComponent(newpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TGLLAHIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NAMA_LENGKAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TGLLAHIR, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pANELLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateDateBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pANELLayout.createSequentialGroup()
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jPasswordField)
                                    .addComponent(jTextPhoneNumber)
                                    .addComponent(jScrollPane2)))
                            .addGroup(pANELLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(radioButtonMale)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonFemale))))
                    .addGroup(pANELLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        pANELLayout.setVerticalGroup(
            pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_LENGKAP, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_LENGKAP1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonMale)
                    .addComponent(radioButtonFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(newpassword, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jTextPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateDateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TGLLAHIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 39, Short.MAX_VALUE)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TGLLAHIR1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JButton getButtonCreateAccount() {
        return buttonCreateAccount;
    }

    public JButton getButtonBackToLogin() {
        return buttonBackToLogin;
    }

    public JDateChooser getjDateDateBirth() {
        return jDateDateBirth;
    }

    public JPasswordField getjPasswordField1() {
        return jPasswordField;
    }

    public JTextArea getjTextAreaAddress() {
        return jTextAreaAddress;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public JTextField getjTextPhoneNumber() {
        return jTextPhoneNumber;
    }

    public void setjDateDateBirth(Date birthDate) {
        this.jDateDateBirth.setDate(birthDate);
    }

    public void setjPasswordField(String password) {
        this.jPasswordField.setText(password);
    }

    public void setjTextAreaAddress(String address) {
        this.jTextAreaAddress.setText(address);
    }

    public void setjTextFieldEmail(String email) {
        this.jTextFieldEmail.setText(email);
    }

    public void setjTextFieldName(String name) {
        this.jTextFieldName.setText(name);
    }

    public JRadioButton getRadioButtonFemale() {
        return radioButtonFemale;
    }

    public JRadioButton getRadioButtonMale() {
        return radioButtonMale;
    }
    
    public void addActionListener(ActionListener x) {
        this.buttonCreateAccount.addActionListener(x);
        this.buttonBackToLogin.addActionListener(x);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAMA_LENGKAP;
    private javax.swing.JLabel NAMA_LENGKAP1;
    private javax.swing.JLabel TGLLAHIR;
    private javax.swing.JLabel TGLLAHIR1;
    private javax.swing.JButton buttonBackToLogin;
    private javax.swing.JButton buttonCreateAccount;
    private javax.swing.ButtonGroup genderButtonGroup;
    private com.toedter.calendar.JDateChooser jDateDateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextPhoneNumber;
    private javax.swing.JLabel labelKeterangan;
    private javax.swing.JLabel newEmail;
    private javax.swing.JLabel newpassword;
    private javax.swing.JLabel newpassword1;
    private javax.swing.JPanel pANEL;
    private javax.swing.JRadioButton radioButtonFemale;
    private javax.swing.JRadioButton radioButtonMale;
    // End of variables declaration//GEN-END:variables
}
