/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.toedter.calendar.JDateChooser;
import java.awt.event.ActionListener;
import java.sql.Date;
import javax.swing.JButton;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author ganjarggt
 */
public class RegisterNewLibrarianView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterNewLibrarian
     */
    public RegisterNewLibrarianView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pANEL1 = new javax.swing.JPanel();
        NAMA_LENGKAP2 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        newEmail1 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        newpassword2 = new javax.swing.JLabel();
        jPasswordField = new javax.swing.JPasswordField();
        TGLLAHIR2 = new javax.swing.JLabel();
        TGLLAHIR3 = new javax.swing.JLabel();
        buttonCreateAccount = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jDateDateBirth = new com.toedter.calendar.JDateChooser();
        NAMA_LENGKAP3 = new javax.swing.JLabel();
        radioButtonMale = new javax.swing.JRadioButton();
        radioButtonFemale = new javax.swing.JRadioButton();
        newpassword3 = new javax.swing.JLabel();
        jTextPhoneNumber = new javax.swing.JTextField();
        buttonBackToLogin = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/telyu.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Form Regisrasi");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pANEL1.setBackground(new java.awt.Color(153, 153, 153));
        pANEL1.setForeground(new java.awt.Color(153, 153, 153));

        NAMA_LENGKAP2.setBackground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        NAMA_LENGKAP2.setForeground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP2.setText("NAMA LENGKAP");

        jTextFieldName.setBackground(new java.awt.Color(204, 204, 204));

        newEmail1.setBackground(new java.awt.Color(255, 255, 255));
        newEmail1.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newEmail1.setForeground(new java.awt.Color(255, 255, 255));
        newEmail1.setText("E-MAIL");

        jTextFieldEmail.setBackground(new java.awt.Color(204, 204, 204));

        newpassword2.setBackground(new java.awt.Color(255, 255, 255));
        newpassword2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newpassword2.setForeground(new java.awt.Color(255, 255, 255));
        newpassword2.setText("PASSWORD");

        jPasswordField.setBackground(new java.awt.Color(204, 204, 204));

        TGLLAHIR2.setBackground(new java.awt.Color(255, 255, 255));
        TGLLAHIR2.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        TGLLAHIR2.setForeground(new java.awt.Color(255, 255, 255));
        TGLLAHIR2.setText("TANGGAL LAHIR");

        TGLLAHIR3.setBackground(new java.awt.Color(255, 255, 255));
        TGLLAHIR3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        TGLLAHIR3.setForeground(new java.awt.Color(255, 255, 255));
        TGLLAHIR3.setText("ALAMAT");

        buttonCreateAccount.setBackground(new java.awt.Color(102, 102, 102));
        buttonCreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        buttonCreateAccount.setText("BUAT AKUN");

        jTextAreaAddress.setBackground(new java.awt.Color(204, 204, 204));
        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jScrollPane3.setViewportView(jTextAreaAddress);

        jDateDateBirth.setBackground(new java.awt.Color(204, 204, 204));

        NAMA_LENGKAP3.setBackground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        NAMA_LENGKAP3.setForeground(new java.awt.Color(255, 255, 255));
        NAMA_LENGKAP3.setText("JENIS KELAMIN");

        radioButtonMale.setBackground(new java.awt.Color(153, 153, 153));
        radioButtonMale.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonMale.setText("Laki-Laki");
        radioButtonMale.setToolTipText("");

        radioButtonFemale.setBackground(new java.awt.Color(153, 153, 153));
        radioButtonFemale.setForeground(new java.awt.Color(255, 255, 255));
        radioButtonFemale.setText("Perempuan");

        newpassword3.setBackground(new java.awt.Color(255, 255, 255));
        newpassword3.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        newpassword3.setForeground(new java.awt.Color(255, 255, 255));
        newpassword3.setText("NOMOR HP");

        jTextPhoneNumber.setBackground(new java.awt.Color(204, 204, 204));

        buttonBackToLogin.setBackground(new java.awt.Color(102, 102, 102));
        buttonBackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonBackToLogin.setText("KEMBALI");

        javax.swing.GroupLayout pANEL1Layout = new javax.swing.GroupLayout(pANEL1);
        pANEL1.setLayout(pANEL1Layout);
        pANEL1Layout.setHorizontalGroup(
            pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pANEL1Layout.createSequentialGroup()
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pANEL1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(NAMA_LENGKAP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newEmail1)
                                .addComponent(newpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TGLLAHIR3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(NAMA_LENGKAP3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(newpassword3, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TGLLAHIR2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pANEL1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDateDateBirth, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(pANEL1Layout.createSequentialGroup()
                                        .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextFieldEmail)
                                    .addComponent(jPasswordField)
                                    .addComponent(jTextPhoneNumber)
                                    .addComponent(jScrollPane3)))
                            .addGroup(pANEL1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(radioButtonMale)
                                .addGap(18, 18, 18)
                                .addComponent(radioButtonFemale))))
                    .addGroup(pANEL1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        pANEL1Layout.setVerticalGroup(
            pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pANEL1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_LENGKAP2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NAMA_LENGKAP3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioButtonMale)
                    .addComponent(radioButtonFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newEmail1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField)
                    .addComponent(newpassword2, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpassword3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextPhoneNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDateDateBirth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TGLLAHIR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 39, Short.MAX_VALUE)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TGLLAHIR3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pANEL1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBackToLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/telyu.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Form Registrasi Pustakawan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(0, 6, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pANEL1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pANEL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public JButton getButtonCreateAccount() {
        return buttonCreateAccount;
    }

    public JButton getButtonBackToLogin() {
        return buttonBackToLogin;
    }

    public JDateChooser getjDateDateBirth() {
        return jDateDateBirth;
    }

    public JPasswordField getjPasswordField1() {
        return jPasswordField;
    }

    public JTextArea getjTextAreaAddress() {
        return jTextAreaAddress;
    }

    public JTextField getjTextFieldEmail() {
        return jTextFieldEmail;
    }

    public JTextField getjTextFieldName() {
        return jTextFieldName;
    }

    public JTextField getjTextPhoneNumber() {
        return jTextPhoneNumber;
    }

    public void setjDateDateBirth(Date birthDate) {
        this.jDateDateBirth.setDate(birthDate);
    }

    public void setjPasswordField(String password) {
        this.jPasswordField.setText(password);
    }

    public void setjTextAreaAddress(String address) {
        this.jTextAreaAddress.setText(address);
    }

    public void setjTextFieldEmail(String email) {
        this.jTextFieldEmail.setText(email);
    }

    public void setjTextFieldName(String name) {
        this.jTextFieldName.setText(name);
    }

    public JRadioButton getRadioButtonFemale() {
        return radioButtonFemale;
    }

    public JRadioButton getRadioButtonMale() {
        return radioButtonMale;
    }
    
    public void addActionListener(ActionListener x) {
        this.buttonCreateAccount.addActionListener(x);
        this.buttonBackToLogin.addActionListener(x);
    }     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NAMA_LENGKAP2;
    private javax.swing.JLabel NAMA_LENGKAP3;
    private javax.swing.JLabel TGLLAHIR2;
    private javax.swing.JLabel TGLLAHIR3;
    private javax.swing.JButton buttonBackToLogin;
    private javax.swing.JButton buttonCreateAccount;
    private com.toedter.calendar.JDateChooser jDateDateBirth;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextPhoneNumber;
    private javax.swing.JLabel newEmail1;
    private javax.swing.JLabel newpassword2;
    private javax.swing.JLabel newpassword3;
    private javax.swing.JPanel pANEL1;
    private javax.swing.JRadioButton radioButtonFemale;
    private javax.swing.JRadioButton radioButtonMale;
    // End of variables declaration//GEN-END:variables
}
